### ISSUE TITLE
Failed at the sharp@0.18.2 install script.

### ISSUE THREAD

**Issue by Gimpy3887** [devsnek/retrocord#20]
C:\Users\Gimpy\AppData\Roaming\npm\node_modules\retrocord\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Gimpy\AppData\Roaming\npm\node_modules\retrocord\node_modules\sharp
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^3.0.0 but none was installed.
npm WARN discord.js@12.0.0-dev requires a peer of node-opus@^0.2.5 but none was installed.
npm WARN discord.js@12.0.0-dev requires a peer of opusscript@^0.0.3 but none was installed.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.1 but none was installed.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.5.1 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.18.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gimpy\AppData\Roaming\npm-cache\_logs\2017-08-12T12_47_09_418Z-debug.log

C:\WINDOWS\system32>

> Can't find Python executable

I already have the environmental variable set. :/

**Comment by devsnek** [comment]
Install python for node gyp
